version: "3.9"

services:
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
    networks:
      - app

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: npm run dev
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    networks:
      - app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: npm run dev
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  db-data:
